---
#- name: Add DNS Entry to Enable Subscription to RHN
#  lineinfile:
#    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
#    line: "DNS1=209.132.186.218"
  #when: inventory_hostname.find(10.) == -1

#- name: Change DNS IP to External IP to Enable Subscription to RHN
#  replace:
#    dest: /etc/resolv.conf
#    regexp: "nameserver .{0,50}"
#    replace: "nameserver 209.132.186.218"
#  #when: hostvars['127.0.0.1']['openstack_env'] == 'public'

#- name: Subscribe the host
#  redhat_subscription:
#    state: present
#    username: "{{ rhn_user }}"
#    password: "{{ rhn_password }}"
#    autosubscribe: true
#  when: os1_distro_variant == 'rhel'

- name: Install Gnome Desktop
  yum: 
    name: "@^GNOME Desktop"
    state: present

- name: Get default runlevel
  command: systemctl get-default
  register: runlevel

- name: Set graphical runlevel
  command: systemctl set-default graphical.target
  when: runlevel.stdout != "graphical.target"

- name: Start Graphical
  service:
    name: graphical.target
    state: started

