---
- name: Copy Default EAP Management User/Group Configuration Files
  become: true
  become_user: root
  copy:
    src: "{{ item }}"
    dest: "{{ eap_standalone_configuration_dir }}"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    mode: "755"
  with_items:
    - mgmt-users.properties
    - mgmt-groups.properties  
