---
# borrowed from
# http://www.opensourcerers.org/how-to-setup-jboss-eap-with-rhel-7-systemd-linuxes/
# http://www.dmartin.es/2014/07/jboss-eap-6-as-rhel-7-service/

- name: Create jboss-eap Service Conf Directory
  file:
    path: "{{ eap_service_conf_dir }}"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    state: directory
    mode: "755"

- name: Copy jboss-eap Service Conf File
  copy:
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    src: jboss-eap.conf
    dest: "{{ eap_service_conf_file }}"
    mode: "755"

- name: Create jboss-eap Service Log Directory
  file:
    path: "{{ eap_service_log_dir }}"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    state: directory
    mode: "755"

- name: Create jboss-eap Service Runtime Data Directory
  file:
    path: "{{ eap_service_data_dir }}"
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    state: directory
    mode: "755"

- name: Copy jboss-eap systemd Unit File
  copy:
    owner: "{{ jboss_user }}"
    group: "{{ jboss_group }}"
    src: jboss-eap-standalone.service
    dest: "{{ eap_service_file }}"
    mode: "755"
  notify:
    - Reload systemd
    - Start and Enable jboss-eap Service # This feels a little hacky
