---
# Installs a BPM Suite via Red Hat internal downloads
# Update these to reflect your organizations artifact repos

#eap_artifact_repo: http://files.justinholmes.co
#eap_artifact_name: jboss-eap-6.4.5-full-build.zip
eap_artifact_repo: /Volumes/JetDrive/Installables/JBoss
eap_artifact_name: jboss-eap-7.1.0.zip

eap_unarchive_temp_dest: /tmp/eap
eap_dest: /opt/eap

eap_patch_artifact_repo: /Volumes/JetDrive/Installables/JBoss
eap_patch_artifact_name: jboss-eap-7.1.3-patch.zip

eap_service_conf_dir: /etc/eap
eap_service_conf_file: /etc/eap/jboss-eap.conf
eap_service_log_dir: /var/log/jboss-eap
eap_service_data_dir: /var/run/jboss-eap
eap_service_file: /etc/systemd/system/jboss-eap-standalone.service

eap_runtime_conf_file: /opt/eap/bin/standalone.conf
eap_standalone_configuration_dir: /opt/eap/standalone/configuration/

eap_bind_web_interface: true
eap_bind_management_interface: false

jboss_user: jboss
jboss_group: jboss
